
sudo: required

services:
  - docker
  
language: node_js
node_js:
  - "6"
  
notifications:
  email:
    on_success: never
  
before_install:
  - npm i -g binci
  
install:
  - binci install
  
script:
  - binci test
  
after_success:
  - sudo chmod -R 777 .yarn-cache/ && sudo chmod -R 777 node_modules/ && sudo chmod -R 777 ~/.npm
  - npm i -g codecov
  - codecov -f coverage/lcov.info 